name: ialarm_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  go_router: ^14.8.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/sonido.png
    - assets/images/logo.png
    - assets/images/foto.png
    - assets/images/nombreApp.png
    - assets/
    - assets/images/
